name: CI-Create-Dashboard
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  REGISTRY: <name of registry>
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Code Base
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_and_push:
    runs-on: ubuntu-20.04
    name: Build and push docker image
    needs: lint
    outputs:
      commit_hash: ${{ steps.commit_hash.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '11'
      - name: Install ant
        run: sudo apt install -y ant    
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
      - id: commit_hash
        run: echo “::set-output name=commit_hash::${GITHUB_SHA::7}”
      - name: Login to <registry>
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}:${{ steps.commit_hash.outputs.commit_hash }}
